export const HANGUL_DATA = {
  consonants: [
    { char: "ㄱ", romanization: "g / k", sound: "Like 'g' in 'go' at start; 'k' at end", ipa: "[k/g]" },
    { char: "ㄴ", romanization: "n", sound: "Like 'n' in 'no'", ipa: "[n]" },
    { char: "ㄷ", romanization: "d / t", sound: "Like 'd' in 'do' at start; 't' at end", ipa: "[d/t]" },
    { char: "ㄹ", romanization: "r / l", sound: "Like 'r' between vowels; 'l' at end of syllable", ipa: "[ɾ/l]" },
    { char: "ㅁ", romanization: "m", sound: "Like 'm' in 'map'", ipa: "[m]" },
    { char: "ㅂ", romanization: "b / p", sound: "Like 'b' in 'big' at start; 'p' at end", ipa: "[b/p]" },
    { char: "ㅅ", romanization: "s / sh", sound: "Like 's' in 'sun'; 'sh' before 'i'", ipa: "[s/ɕ]" },
    { char: "ㅇ", romanization: "ng / silent", sound: "Silent at syllable start; 'ng' as final consonant (batchim)", ipa: "[∅/ŋ]" },
    { char: "ㅈ", romanization: "j / ch", sound: "Like 'j' in 'job'; softer like 'ch'", ipa: "[dʑ]" },
    { char: "ㅊ", romanization: "ch", sound: "Like 'ch' in 'church' (aspirated)", ipa: "[tɕʰ]" },
    { char: "ㅋ", romanization: "k", sound: "Like 'k' in 'kite' (strongly aspirated)", ipa: "[kʰ]" },
    { char: "ㅌ", romanization: "t", sound: "Like 't' in 'top' (strongly aspirated)", ipa: "[tʰ]" },
    { char: "ㅍ", romanization: "p", sound: "Like 'p' in 'pie' (strongly aspirated)", ipa: "[pʰ]" },
    { char: "ㅎ", romanization: "h", sound: "Like 'h' in 'hello'", ipa: "[h]" },
    { char: "ㄲ", romanization: "kk", sound: "Tense 'k' — like holding your breath before 'k'", ipa: "[k͈]" },
    { char: "ㄸ", romanization: "tt", sound: "Tense 't'", ipa: "[t͈]" },
    { char: "ㅃ", romanization: "pp", sound: "Tense 'p'", ipa: "[p͈]" },
    { char: "ㅆ", romanization: "ss", sound: "Tense 's'", ipa: "[s͈]" },
    { char: "ㅉ", romanization: "jj", sound: "Tense 'j'", ipa: "[tɕ͈]" },
  ],
  vowels: [
    { char: "ㅏ", romanization: "a", sound: "Like 'a' in 'father'", example: "아 (a)" },
    { char: "ㅑ", romanization: "ya", sound: "Like 'ya' in 'yard'", example: "야 (ya)" },
    { char: "ㅓ", romanization: "eo", sound: "Like 'u' in 'up' (rounded)", example: "어 (eo)" },
    { char: "ㅕ", romanization: "yeo", sound: "Like 'yu' in 'yuck'", example: "여 (yeo)" },
    { char: "ㅗ", romanization: "o", sound: "Like 'o' in 'go'", example: "오 (o)" },
    { char: "ㅛ", romanization: "yo", sound: "Like 'yo' in 'yoga'", example: "요 (yo)" },
    { char: "ㅜ", romanization: "u", sound: "Like 'oo' in 'moon'", example: "우 (u)" },
    { char: "ㅠ", romanization: "yu", sound: "Like 'you'", example: "유 (yu)" },
    { char: "ㅡ", romanization: "eu", sound: "No English equivalent — lips spread, round in back", example: "으 (eu)" },
    { char: "ㅣ", romanization: "i", sound: "Like 'ee' in 'see'", example: "이 (i)" },
    { char: "ㅐ", romanization: "ae", sound: "Like 'e' in 'bed'", example: "애 (ae)" },
    { char: "ㅔ", romanization: "e", sound: "Like 'e' in 'bed' (same as ㅐ in modern Korean)", example: "에 (e)" },
    { char: "ㅘ", romanization: "wa", sound: "Like 'wa' in 'water'", example: "와 (wa)" },
    { char: "ㅝ", romanization: "wo", sound: "Like 'wo' in 'won't'", example: "워 (wo)" },
    { char: "ㅢ", romanization: "ui", sound: "Slide from 'eu' to 'i'", example: "의 (ui)" },
  ],
  syllableStructure: {
    title: "How Syllable Blocks Work",
    steps: [
      { label: "CV", example: "가 (ga)", desc: "Consonant + Vowel — most basic form" },
      { label: "CVV", example: "과 (gwa)", desc: "Consonant + Compound Vowel" },
      { label: "CVC (Batchim)", example: "밥 (bap)", desc: "Consonant + Vowel + Final Consonant (Batchim ㅂ)" },
      { label: "CVCC", example: "닭 (dak)", desc: "Two batchim consonants — only one sounds" },
    ],
    note: "Every Korean syllable must have an initial consonant (use ㅇ as silent placeholder if it starts with a vowel) and a vowel. The final consonant (받침 batchim) is optional.",
  },
  batchimRules: [
    { batchim: "ㄱ, ㄲ, ㅋ", sound: "[k]", example: "먹 → [먹]", note: "All reduce to a sharp unreleased 'k'" },
    { batchim: "ㄴ", sound: "[n]", example: "눈 → [nun]", note: "Nasal 'n'" },
    { batchim: "ㄷ, ㅅ, ㅆ, ㅈ, ㅊ, ㅎ", sound: "[t]", example: "옷 → [옫]", note: "All reduce to an unreleased 't'" },
    { batchim: "ㄹ", sound: "[l]", example: "말 → [mal]", note: "Lateral 'l'" },
    { batchim: "ㅁ", sound: "[m]", example: "봄 → [bom]", note: "Nasal 'm'" },
    { batchim: "ㅂ, ㅍ", sound: "[p]", example: "입 → [ip]", note: "Unreleased 'p'" },
    { batchim: "ㅇ", sound: "[ŋ]", example: "강 → [kaŋ]", note: "Like 'ng' in 'song'" },
  ],
  soundChangeRules: [
    {
      name: "Linking (연음, Yeon-eum)",
      rule: "When a batchim is followed by a syllable starting with ㅇ (silent), the batchim sound 'links' into the next syllable.",
      examples: [
        { before: "먹어요", after: "머거요 [meo-geo-yo]", note: "ㄱ links to the ㅇ of 어" },
        { before: "밥이에요", after: "바비에요 [ba-bi-e-yo]", note: "ㅂ links to ㅇ of 이" },
      ],
    },
    {
      name: "Nasalisation (비음화, Bi-eum-hwa)",
      rule: "Stop consonants (ㄱ, ㄷ, ㅂ) change to their nasal counterparts (ㅇ, ㄴ, ㅁ) when followed by a nasal consonant (ㄴ, ㅁ).",
      examples: [
        { before: "국물", after: "궁물 [gung-mul]", note: "ㄱ + ㅁ → ㅇ + ㅁ" },
        { before: "받는다", after: "반는다 [ban-neun-da]", note: "ㄷ + ㄴ → ㄴ + ㄴ" },
        { before: "입문", after: "임문 [im-mun]", note: "ㅂ + ㅁ → ㅁ + ㅁ" },
      ],
    },
    {
      name: "Lateralisation (유음화, Yu-eum-hwa)",
      rule: "ㄴ changes to ㄹ when adjacent to ㄹ.",
      examples: [
        { before: "신라", after: "실라 [sil-la]", note: "ㄴ + ㄹ → ㄹ + ㄹ" },
        { before: "칼날", after: "칼랄 [kal-lal]", note: "ㄹ + ㄴ → ㄹ + ㄹ" },
      ],
    },
    {
      name: "Aspiration (격음화, Gyeok-eum-hwa)",
      rule: "ㅎ combines with stop consonants to produce aspirated versions: ㅎ+ㄱ→ㅋ, ㅎ+ㄷ→ㅌ, ㅎ+ㅂ→ㅍ, ㅎ+ㅈ→ㅊ",
      examples: [
        { before: "좋다", after: "조타 [jo-ta]", note: "ㅎ + ㄷ → ㅌ" },
        { before: "넣고", after: "너코 [neo-ko]", note: "ㅎ + ㄱ → ㅋ" },
      ],
    },
    {
      name: "Tensification (경음화, Gyeong-eum-hwa)",
      rule: "Plain consonants (ㄱ,ㄷ,ㅂ,ㅅ,ㅈ) become tense (ㄲ,ㄸ,ㅃ,ㅆ,ㅉ) after stop batchim consonants.",
      examples: [
        { before: "학교", after: "학꾜 [hak-kyo]", note: "ㄱ batchim + ㄱ → ㄲ" },
        { before: "식당", after: "식땅 [sik-ttang]", note: "ㄱ batchim + ㄷ → ㄸ" },
      ],
    },
    {
      name: "ㅎ Weakening (ㅎ 약화)",
      rule: "ㅎ is often weakened or dropped entirely between voiced sounds (vowels or sonorants).",
      examples: [
        { before: "전화", after: "저놔 [jeo-nwa]", note: "ㅎ weakens between vowels" },
        { before: "결혼", after: "겨론 [gyeo-ron]", note: "ㅎ drops, ㄹ links" },
      ],
    },
  ],
};
