export const KOREAN_NUMBERS = {
  sino: {
    title: "Sino-Korean Numbers (한자어 수사)",
    description:
      "Sino-Korean numbers are derived from Chinese. They are used for dates, money, phone numbers, addresses, minutes, and large quantities.",
    usedFor: [
      "Dates (월 month, 일 day,년 year)",
      "Money (원 won)",
      "Phone numbers",
      "Minutes (분)",
      "Floors of buildings (층)",
      "Large numbers (100+)",
    ],
    digits: [
      { num: 0, korean: "영 / 공", romanization: "yeong / gong", note: "영 in math; 공 in phone numbers" },
      { num: 1, korean: "일", romanization: "il", note: "" },
      { num: 2, korean: "이", romanization: "i", note: "" },
      { num: 3, korean: "삼", romanization: "sam", note: "" },
      { num: 4, korean: "사", romanization: "sa", note: "" },
      { num: 5, korean: "오", romanization: "o", note: "" },
      { num: 6, korean: "육", romanization: "yuk", note: "" },
      { num: 7, korean: "칠", romanization: "chil", note: "" },
      { num: 8, korean: "팔", romanization: "pal", note: "" },
      { num: 9, korean: "구", romanization: "gu", note: "" },
    ],
    unitWords: [
      { value: "10", korean: "십 (十)", romanization: "sip", example: "이십 = 20, 삼십 = 30" },
      { value: "100", korean: "백 (百)", romanization: "baek", example: "이백 = 200, 오백 = 500" },
      { value: "1,000", korean: "천 (千)", romanization: "cheon", example: "삼천 = 3,000, 팔천 = 8,000" },
      { value: "10,000", korean: "만 (萬)", romanization: "man", example: "오만 = 50,000, 십만 = 100,000" },
      { value: "100,000,000", korean: "억 (億)", romanization: "eok", example: "일억 = 100,000,000" },
      { value: "1,000,000,000,000", korean: "조 (兆)", romanization: "jo", example: "일조 = 1 trillion" },
    ],
    formationRules: [
      {
        title: "Tens (십)",
        rule: "Attach the digit before 십. For exactly 10, just say 십 (no 일십).",
        examples: [
          { number: 10, expression: "십", breakdown: "십 alone" },
          { number: 11, expression: "십일", breakdown: "십 + 일" },
          { number: 25, expression: "이십오", breakdown: "이 + 십 + 오" },
          { number: 99, expression: "구십구", breakdown: "구 + 십 + 구" },
        ],
      },
      {
        title: "Hundreds (백)",
        rule: "Attach digit before 백. For exactly 100, say 백 (not 일백).",
        examples: [
          { number: 100, expression: "백", breakdown: "백 alone" },
          { number: 101, expression: "백일", breakdown: "백 + 일" },
          { number: 250, expression: "이백오십", breakdown: "이 + 백 + 오 + 십" },
          { number: 999, expression: "구백구십구", breakdown: "구 + 백 + 구 + 십 + 구" },
        ],
      },
      {
        title: "Thousands (천)",
        rule: "Attach digit before 천. For exactly 1,000, say 천 (not 일천).",
        examples: [
          { number: 1000, expression: "천", breakdown: "천 alone" },
          { number: 1500, expression: "천오백", breakdown: "천 + 오 + 백" },
          { number: 3200, expression: "삼천이백", breakdown: "삼 + 천 + 이 + 백" },
          { number: 9999, expression: "구천구백구십구", breakdown: "구천 + 구백 + 구십 + 구" },
        ],
      },
      {
        title: "Ten-thousands (만)",
        rule: "Korean groups large numbers by 만 (10,000) not 1,000. Think in units of 만.",
        examples: [
          { number: 10000, expression: "만", breakdown: "만 alone (not 십천!)" },
          { number: 15000, expression: "만오천", breakdown: "만 + 오 + 천" },
          { number: 50000, expression: "오만", breakdown: "오 + 만" },
          { number: 100000, expression: "십만", breakdown: "십 + 만" },
          { number: 1000000, expression: "백만", breakdown: "백 + 만" },
          { number: 10000000, expression: "천만", breakdown: "천 + 만" },
        ],
      },
      {
        title: "Hundred-millions (억)",
        rule: "억 (100,000,000) is the next unit after 만. It follows the same logic: Digit/Group before 억 multiplies exactly how many 100-millions exist.",
        examples: [
          { number: 100000000, expression: "억 (or 일억)", breakdown: "100 million" },
          { number: 200000000, expression: "이억", breakdown: "이(2) × 억(100M)" },
          { number: 1000000000, expression: "십억", breakdown: "십(10) × 억 = 1 Billion" },
          { number: 10000000000, expression: "백억", breakdown: "백(100) × 억 = 10 Billion" },
          { number: 100000000000, expression: "천억", breakdown: "천(1000) × 억 = 100 Billion" },
        ],
      },
      {
        title: "Trillions (조)",
        rule: "조 (1,000,000,000,000) is the unit for 1 Trillion. Used mostly in economics or macro-statistics.",
        examples: [
          { number: 1000000000000, expression: "조 (or 일조)", breakdown: "1 Trillion" },
          { number: 5000000000000, expression: "오조", breakdown: "오(5) × 조" },
          { number: 10000000000000, expression: "십조", breakdown: "십(10) × 조 = 10 Trillion" },
        ],
      },
      {
        title: "Chaining Units (조 → 억 → 만)",
        rule: "When writing large numbers, work from left to right. Each 4-digit block gets its unit (조, 억, 만). Smaller units below 10,000 don't have a specific 'block unit' at the end.",
        examples: [
          { number: 12345678, expression: "일천이백삼십사만 오천육백칠십팔", breakdown: "1234 [만] then 5678" },
          { number: 100050000, expression: "일억 오만", breakdown: "1 [억] then 5 [만]" },
        ],
      },
      {
        title: "Important: 일 is dropped for 백, 천 but NOT for 만, 억, 조",
        rule: "For 백(100) and 천(1,000) you don't say 일. But for 만(10,000), 억(100,000,000), and 조(trillion), you CAN say 일 if it is at the very beginning of the number to be formal.",
        examples: [
          { number: 100, expression: "백 ✅", breakdown: "NOT 일백 ❌" },
          { number: 1000, expression: "천 ✅", breakdown: "NOT 일천 ❌" },
          { number: 10000, expression: "만 (or 일만)", breakdown: "일 is optional here" },
          { number: 100000000, expression: "억 (or 일억)", breakdown: "일 is very common for 1-억" },
        ],
      },
    ],
    practiceExamples: [
      { number: 2024, expression: "이천이십사", use: "Year (년)" },
      { number: 3, expression: "삼", use: "Month 3 → 삼월" },
      { number: 15, expression: "십오", use: "Day 15 → 십오일" },
      { number: 50000, expression: "오만", use: "50,000 won → 오만 원" },
      { number: 1234, expression: "천이백삼십사", use: "Address / Number" },
    ],
  },

  native: {
    title: "Native Korean Numbers (순우리말 수사)",
    description:
      "Native Korean numbers come from old Korean roots. They are used for counting objects, people, age, and hours.",
    usedFor: [
      "Counting objects with counters (개, 마리, 권...)",
      "Age (살)",
      "Hours of time (시)",
      "People (명, 분)",
      "Floors (층) in casual speech",
    ],
    digits: [
      { num: 1, full: "하나", shortened: "한", romanization: "hana / han", note: "하나 alone; 한 before a counter" },
      { num: 2, full: "둘", shortened: "두", romanization: "dul / du", note: "둘 alone; 두 before a counter" },
      { num: 3, full: "셋", shortened: "세", romanization: "set / se", note: "셋 alone; 세 before a counter" },
      { num: 4, full: "넷", shortened: "네", romanization: "net / ne", note: "넷 alone; 네 before a counter" },
      { num: 5, full: "다섯", shortened: "다섯", romanization: "daseot", note: "Same before counter" },
      { num: 6, full: "여섯", shortened: "여섯", romanization: "yeoseot", note: "Same before counter" },
      { num: 7, full: "일곱", shortened: "일곱", romanization: "ilgop", note: "Same before counter" },
      { num: 8, full: "여덟", shortened: "여덟", romanization: "yeodeol", note: "Same before counter" },
      { num: 9, full: "아홉", shortened: "아홉", romanization: "ahop", note: "Same before counter" },
      { num: 10, full: "열", shortened: "열", romanization: "yeol", note: "Same before counter" },
      { num: 20, full: "스물", shortened: "스무", romanization: "seumul / seumu", note: "스물 alone; 스무 before a counter" },
      { num: 30, full: "서른", shortened: "서른", romanization: "seoreun", note: "" },
      { num: 40, full: "마흔", shortened: "마흔", romanization: "maheun", note: "" },
      { num: 50, full: "쉰", shortened: "쉰", romanization: "shwin", note: "" },
      { num: 60, full: "예순", shortened: "예순", romanization: "yesun", note: "" },
      { num: 70, full: "일흔", shortened: "일흔", romanization: "ilheun", note: "" },
      { num: 80, full: "여든", shortened: "여든", romanization: "yeodeun", note: "" },
      { num: 90, full: "아흔", shortened: "아흔", romanization: "aheun", note: "" },
      { num: 100, full: "백", shortened: "백", romanization: "baek", note: "Switches to Sino-Korean at 100!" },
    ],
    formationRules: [
      {
        title: "Forming numbers 11–19",
        rule: "열 (10) + individual digit. The digit form does NOT shorten before 열.",
        examples: [
          { number: 11, expression: "열하나", breakdown: "열 + 하나" },
          { number: 14, expression: "열넷", breakdown: "열 + 넷" },
          { number: 19, expression: "열아홉", breakdown: "열 + 아홉" },
        ],
      },
      {
        title: "Forming numbers 21–99",
        rule: "Tens word + digit. The digit form does NOT shorten before a tens word.",
        examples: [
          { number: 21, expression: "스물하나", breakdown: "스물 + 하나" },
          { number: 35, expression: "서른다섯", breakdown: "서른 + 다섯" },
          { number: 48, expression: "마흔여덟", breakdown: "마흔 + 여덟" },
          { number: 99, expression: "아흔아홉", breakdown: "아흔 + 아홉" },
        ],
      },
      {
        title: "Shortening before counters",
        rule: "하나→한, 둘→두, 셋→세, 넷→네, 스물→스무 when a counter word follows immediately.",
        examples: [
          { number: 1, expression: "한 개", breakdown: "한 + 개 (thing) — NOT 하나 개" },
          { number: 2, expression: "두 명", breakdown: "두 + 명 (person)" },
          { number: 3, expression: "세 마리", breakdown: "세 + 마리 (animal)" },
          { number: 20, expression: "스무 살", breakdown: "스무 + 살 (age)" },
        ],
      },
      {
        title: "Upper limit: Native numbers stop at 99",
        rule: "Native Korean numbers only go up to 99. For 100+, switch back to Sino-Korean (백, 천, 만...).",
        examples: [
          { number: 99, expression: "아흔아홉 (Native)", breakdown: "Last native number" },
          { number: 100, expression: "백 (Sino)", breakdown: "Switches to Sino-Korean" },
        ],
      },
    ],
    counters: [
      { counter: "개", meaning: "General objects / things", example: "사과 두 개 — two apples" },
      { counter: "명 / 분", meaning: "People (명 casual, 분 polite)", example: "두 명 — two people" },
      { counter: "마리", meaning: "Animals", example: "강아지 세 마리 — three dogs" },
      { counter: "권", meaning: "Books / bound items", example: "책 한 권 — one book" },
      { counter: "잔", meaning: "Cups / glasses of drink", example: "커피 두 잔 — two coffees" },
      { counter: "병", meaning: "Bottles", example: "물 한 병 — one bottle of water" },
      { counter: "장", meaning: "Flat/thin sheets (paper, tickets)", example: "종이 세 장 — three sheets" },
      { counter: "시", meaning: "O'clock (hours) — Sino hours use 분", example: "두 시 — 2 o'clock" },
      { counter: "살", meaning: "Age (years old)", example: "스물다섯 살 — 25 years old" },
      { counter: "번", meaning: "Times / occurrences", example: "두 번 — two times" },
    ],
    practiceExamples: [
      { scenario: "I am 28 years old", korean: "스물여덟 살이에요", note: "Native number + 살" },
      { scenario: "3 o'clock", korean: "세 시", note: "Native hour + 시" },
      { scenario: "5 apples", korean: "사과 다섯 개", note: "Native + 개" },
      { scenario: "2 people", korean: "두 명", note: "두 (shortened) + 명" },
      { scenario: "7:30", korean: "일곱 시 삼십 분", note: "Native hour + Sino minutes" },
    ],
  },

  comparison: [
    { context: "Age", system: "Native", example: "스물다섯 살 (25 years old)" },
    { context: "Hours", system: "Native", example: "세 시 (3 o'clock)" },
    { context: "Minutes", system: "Sino", example: "삼십 분 (30 minutes)" },
    { context: "Month", system: "Sino", example: "삼월 (March)" },
    { context: "Day of month", system: "Sino", example: "십오일 (15th)" },
    { context: "Year", system: "Sino", example: "이천이십사년 (2024)" },
    { context: "Money", system: "Sino", example: "오만 원 (50,000 won)" },
    { context: "Counting objects", system: "Native", example: "다섯 개 (5 things)" },
    { context: "Counting people", system: "Native", example: "두 명 (2 people)" },
    { context: "Phone numbers", system: "Sino", example: "공일공... (010...)" },
    { context: "Floors", system: "Sino", example: "삼층 (3rd floor)" },
  ],

  daysAndMonths: {
    daysOfWeek: [
      { korean: "월요일", romanization: "wol-yo-il", meaning: "Monday", hanja: "月 (moon/month)", tip: "월 = Moon" },
      { korean: "화요일", romanization: "hwa-yo-il", meaning: "Tuesday", hanja: "火 (fire)", tip: "화 = Fire" },
      { korean: "수요일", romanization: "su-yo-il", meaning: "Wednesday", hanja: "水 (water)", tip: "수 = Water" },
      { korean: "목요일", romanization: "mok-yo-il", meaning: "Thursday", hanja: "木 (wood/tree)", tip: "목 = Wood" },
      { korean: "금요일", romanization: "geum-yo-il", meaning: "Friday", hanja: "金 (gold/metal)", tip: "금 = Gold" },
      { korean: "토요일", romanization: "to-yo-il", meaning: "Saturday", hanja: "土 (earth/soil)", tip: "토 = Earth" },
      { korean: "일요일", romanization: "il-yo-il", meaning: "Sunday", hanja: "日 (sun/day)", tip: "일 = Sun" },
    ],
    dayMemonic: "The days follow the Five Elements + Sun and Moon: 월(Moon) 화(Fire) 수(Water) 목(Wood) 금(Gold) 토(Earth) 일(Sun). Once you know the elements you'll never forget the days!",
    usefulDayPhrases: [
      { phrase: "오늘이 무슨 요일이에요?", romanization: "oneul-i museun yo-il-ieyo?", meaning: "What day is it today?" },
      { phrase: "오늘은 월요일이에요.", romanization: "oneul-eun wol-yo-il-ieyo.", meaning: "Today is Monday." },
      { phrase: "내일은 화요일이에요.", romanization: "naeil-eun hwa-yo-il-ieyo.", meaning: "Tomorrow is Tuesday." },
      { phrase: "어제는 일요일이었어요.", romanization: "eoje-neun il-yo-il-ieosseoyo.", meaning: "Yesterday was Sunday." },
      { phrase: "주말에 뭐 해요?", romanization: "jumal-e mwo haeyo?", meaning: "What are you doing on the weekend?" },
    ],
    months: [
      { num: 1, korean: "일월", romanization: "il-wol", meaning: "January", breakdown: "일(1) + 월(month)" },
      { num: 2, korean: "이월", romanization: "i-wol", meaning: "February", breakdown: "이(2) + 월(month)" },
      { num: 3, korean: "삼월", romanization: "sam-wol", meaning: "March", breakdown: "삼(3) + 월(month)" },
      { num: 4, korean: "사월", romanization: "sa-wol", meaning: "April", breakdown: "사(4) + 월(month)" },
      { num: 5, korean: "오월", romanization: "o-wol", meaning: "May", breakdown: "오(5) + 월(month)" },
      { num: 6, korean: "유월", romanization: "yu-wol", meaning: "June", breakdown: "육→유 + 월 (sound change!)" },
      { num: 7, korean: "칠월", romanization: "chil-wol", meaning: "July", breakdown: "칠(7) + 월(month)" },
      { num: 8, korean: "팔월", romanization: "pal-wol", meaning: "August", breakdown: "팔(8) + 월(month)" },
      { num: 9, korean: "구월", romanization: "gu-wol", meaning: "September", breakdown: "구(9) + 월(month)" },
      { num: 10, korean: "시월", romanization: "si-wol", meaning: "October", breakdown: "십→시 + 월 (sound change!)" },
      { num: 11, korean: "십일월", romanization: "sip-il-wol", meaning: "November", breakdown: "십일(11) + 월(month)" },
      { num: 12, korean: "십이월", romanization: "sip-i-wol", meaning: "December", breakdown: "십이(12) + 월(month)" },
    ],
    monthNotes: [
      { month: "June (유월)", rule: "육월 → 유월: 육 loses its final consonant ㄱ before 월 due to pronunciation ease." },
      { month: "October (시월)", rule: "십월 → 시월: 십 loses its final consonant ㅂ before 월. Very common spoken form." },
    ],
    usefulDatePhrases: [
      { phrase: "오늘이 며칠이에요?", romanization: "oneul-i myeochil-ieyo?", meaning: "What's today's date?" },
      { phrase: "오늘은 삼월 십팔일이에요.", romanization: "oneul-eun sam-wol sip-pal-il-ieyo.", meaning: "Today is March 18th." },
      { phrase: "제 생일은 오월 오일이에요.", romanization: "je saengil-eun o-wol o-il-ieyo.", meaning: "My birthday is May 5th." },
      { phrase: "이천이십오년 일월 일일", romanization: "icheon-isip-o nyeon il-wol il-il", meaning: "January 1st, 2025" },
    ],
    dateStructure: "Korean dates go: Year(년) → Month(월) → Day(일). E.g. 2025년 3월 18일 = 2025-03-18.",
  },

  time: {
    structure: "Korean time = Native hour (시) + Sino minutes (분). Hours 1–12 use native numbers; minutes use Sino.",
    amPm: [
      { term: "오전", romanization: "o-jeon", meaning: "AM (before noon)", lit: "前 = before" },
      { term: "오후", romanization: "o-hu", meaning: "PM (after noon)", lit: "後 = after" },
      { term: "정오", romanization: "jeong-o", meaning: "Noon / 12:00 PM", lit: "正午 = exact noon" },
      { term: "자정", romanization: "ja-jeong", meaning: "Midnight / 12:00 AM", lit: "子正 = midnight" },
    ],
    hours: [
      { num: 1, korean: "한 시", romanization: "han si" },
      { num: 2, korean: "두 시", romanization: "du si" },
      { num: 3, korean: "세 시", romanization: "se si" },
      { num: 4, korean: "네 시", romanization: "ne si" },
      { num: 5, korean: "다섯 시", romanization: "daseot si" },
      { num: 6, korean: "여섯 시", romanization: "yeoseot si" },
      { num: 7, korean: "일곱 시", romanization: "ilgop si" },
      { num: 8, korean: "여덟 시", romanization: "yeodeol si" },
      { num: 9, korean: "아홉 시", romanization: "ahop si" },
      { num: 10, korean: "열 시", romanization: "yeol si" },
      { num: 11, korean: "열한 시", romanization: "yeolhan si" },
      { num: 12, korean: "열두 시", romanization: "yeoldu si" },
    ],
    minutePatterns: [
      { min: "0", korean: "정각", romanization: "jeong-gak", note: "Exactly on the hour" },
      { min: "5", korean: "오 분", romanization: "o bun", note: "Sino 오" },
      { min: "10", korean: "십 분", romanization: "sip bun", note: "" },
      { min: "15", korean: "십오 분", romanization: "sip-o bun", note: "" },
      { min: "30", korean: "삼십 분", romanization: "sam-sip bun", note: "Also: 반 (ban) = half past" },
      { min: "45", korean: "사십오 분", romanization: "sa-sip-o bun", note: "" },
    ],
    specialMinutes: [
      { term: "반", romanization: "ban", meaning: "Half past (30 min)", example: "세 시 반 = 3:30" },
      { term: "X분 전", romanization: "X bun jeon", meaning: "X minutes TO the hour", example: "열 분 전 두 시 = 1:50 (10 min before 2)" },
      { term: "X시 X분", romanization: "X si X bun", meaning: "Standard: Hour + minutes", example: "두 시 삼십 분 = 2:30" },
    ],
    exampleTimes: [
      { time: "1:00", korean: "한 시", romanization: "han si", breakdown: "Native 1 + 시" },
      { time: "3:30", korean: "세 시 삼십 분 (세 시 반)", romanization: "se si sam-sip bun", breakdown: "Native 3 + 시 + Sino 30 + 분" },
      { time: "7:15", korean: "일곱 시 십오 분", romanization: "ilgop si sip-o bun", breakdown: "Native 7 + 시 + Sino 15 + 분" },
      { time: "9:00 AM", korean: "오전 아홉 시", romanization: "o-jeon ahop si", breakdown: "오전 + Native 9 + 시" },
      { time: "6:45 PM", korean: "오후 여섯 시 사십오 분", romanization: "o-hu yeoseot si sa-sip-o bun", breakdown: "오후 + Native 6 + 시 + Sino 45 + 분" },
      { time: "12:00 PM", korean: "정오", romanization: "jeong-o", breakdown: "Special word for noon" },
    ],
    usefulTimePhrases: [
      { phrase: "지금 몇 시예요?", romanization: "jigeum myeot si-yeyo?", meaning: "What time is it now?" },
      { phrase: "두 시 반이에요.", romanization: "du si ban-ieyo.", meaning: "It's 2:30." },
      { phrase: "오전 열 시에 만나요.", romanization: "o-jeon yeol si-e man-nayo.", meaning: "Let's meet at 10 AM." },
      { phrase: "몇 시에 끝나요?", romanization: "myeot si-e kkeut-nayo?", meaning: "What time does it finish?" },
      { phrase: "다섯 시 삼십 분에 와요.", romanization: "daseot si sam-sip bun-e wayo.", meaning: "Come at 5:30." },
    ],
  },
};

